### ISSUE TITLE
Allowed attribute string value edge cases

### ISSUE THREAD

**Issue by mattrosno** [ibm-telemetry/telemetry-js-config-generator#28]
**Description**

> Tell us more about the problem that you're running into. What did you see? What did you expect to
> see?

This likely needs broken down into more issues, but when running the config generator against this repo, here is the manual cleanup that I had to do:

https://github.com/carbon-design-system/carbon-addons-iot-react/pull/3854/commits/ec74fd5f438c9b63b629c38ecce139477f22453d

- [ ] Double quotes

Some values had double quotes, e.g.:

```yml
        - '"lg"'
        - '"max"'
        - '"md"'
        - '"sm"'
        - '"xl"'
        - '"xs"'
```

- [ ] Prop types

I was surprised to see prop types as valid values, e.g.:

```yml
        - |-
          PropTypes.shape({
            peak: PropTypes.number,
            meterTotal: PropTypes.number,
            meterUnit: PropTypes.string,
            totalFormatter: PropTypes.func,
            legendPosition: PropTypes.string,
            ...ChartColorPropType,
          })
```

- [ ] Empty strings

There were a few empty strings that shouldn't have been there? Maybe these are okay, if it's value to set a prop with an empty string.

```yml
        - ''
```

- [ ] Object.values

I'm guessing we don't want executable JS as valid values? E.g.:

```yml
        - ...Object.values(ITEM_VALUE_KEYS)
```

**Steps to reproduce**

> How do we reproduce the error? Please be as specific as you can.

1. https://github.com/carbon-design-system/carbon-addons-iot-react/pull/3854/commits/ec74fd5f438c9b63b629c38ecce139477f22453d
